version: '2.2'
services:
  es1:
    image: elasticsearch
    container_name: es1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    mem_swappiness: 0
    volumes:
      - ../es-conf:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
    networks:
      - esnet

  es2:
    image: elasticsearch
    container_name: es2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    mem_swappiness: 0
    volumes:
      - ../es-conf:/usr/share/elasticsearch/config
    networks:
      - esnet
    depends_on:
      - es1

  es3:
    image: elasticsearch
    container_name: es3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    mem_swappiness: 0
    volumes:
      - ../es-conf:/usr/share/elasticsearch/config
    networks:
      - esnet
    depends_on:
      - es1
      - es2

  kibana:
    image: kibana
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://es1:9200"
    mem_limit: 1g
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - es1
      - es2
      - es3
      - logstash


  logstash:
    image: logstash
    container_name: logstash
    volumes:
      - ../logstash/pipeline:/etc/logstash/conf.d
    command: ["logstash", "-f", "/etc/logstash/conf.d/logstash.conf"]
    ports:
      - 5000:5000
      - 8080:8080
    networks:
      - esnet
    depends_on:
      - es1
      - es2
      - es3

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
networks:
  esnet:
    driver: bridge
